### ISSUE TITLE
Infinite loading loop

### ISSUE THREAD

**Issue by RoskoDaneworth** [PatnosDD/Hollow-Knight-PsVita#13]
No matter what i try - game never goes past loading screen. Waited like for 5-10 minutes on loading.
Tried every versions of every game-releases. Previous vpk versions dont work as well.
ioplus, libshacccg, kubridge and anything else (overclock including) - installed in right places, all other homebrews work fine.
Have lots of plugins in tai config.txt but hardly anything comes in mind that could interfere with game loading.

**Comment by RoskoDaneworth** [comment]
Update: fixed by rebuilding database. Game loads. But have static screen.
So i hear game sounds and can press buttons and do things - but screen is locked with static image of the loading screen, game image doesnt update.

**Comment by PatnosDD** [comment]
Problem with your vita. Not an issue of the port. Re-check installed plugins.

**Comment by RoskoDaneworth** [comment]
I have found the culprit. Just so that you know and other people too.

Unity-based games/homebrew are Incompatible with plugin TropHax2.0 (unlocks trophies).
I suddenly remembered that i had similar issue with Synergia VN game with static screen.

Hollow Knight port suffers from the same thing. TopHax2.0 plugin makes somehow static screen in unity games. This info should be mentioned in ReadMe.md
