### ISSUE TITLE
Not playable on vita 1000

### ISSUE THREAD

**Issue by nyomen** [PatnosDD/Hollow-Knight-PsVita#15]
No. You think it plays well, but no, it does not.
I installed the thread optimizer, I overclocked, but when you come to the protector the game just stops working on the vita.
Or do you want to play a boss in a souls like game and have every 5 seconds a random 1 second lag?
How anyone call this a working game with that inside. It's prealpha.
and btw... Reducing random textures and making even your own character look like **** in idle animation isn't the way at all. 
Maybe start reducing background textures instead of random sheit everywhere.
So for all the people out there with an overclocked vs1000 (thread optimizer is not even working on 1000) just save your time and not install it.

**Comment by Alesposito00** [comment]
You have played a FREE port, done by a user that have spent his free time to create it. You can play it, or you can try to do something better or, maybe, you can help him. A lot of user know that this port is far from perfection, but we still play it however. Tha fact that we have Hollow Knight on Vita is enough for a large part of the vita user, his vpk has achieved 30k downloads on vitaDB.

**Comment by nyomen** [comment]
> You have played a FREE port, done by a user that have spent his free time to create it. You can play it, or you can try to do something better or, maybe, you can help him. A lot of user know that this port is far from perfection, but we still play it however. Tha fact that we have Hollow Knight on Vita is enough for a large part of the vita user, his vpk has achieved 30k downloads on vitaDB.

I can't help, since it's fakeopensource and he makes money with it.
Or do you see any source files here?
And sure you can play it. But it want to remind people that it's not good, even if it sounds and feels good in the beginning, and I can only speak vor vita 1000.

And btw usually there is a, "what's working" and "what's not working" part in the Readme....

**Comment by PatnosDD** [comment]
Chill..
