### ISSUE TITLE
error when launching

### ISSUE THREAD

**Issue by skewbug** [PatnosDD/Hollow-Knight-PsVita#16]
I followed the instructions and it just doesn't seem to work. Game files were sucessfully patched and nothing seems to be an issue until I launch the bubble.

`An error has occurred in the following application.
(C2-12828-1)
Saved Core File Succeeded.
ux0:data/psp2core-1728418910-0x00001a2d6b-eboot.bin.psp2dmp`

**Comment by PatnosDD** [comment]
You probably dont have the data files in the correct path.

**Comment by skewbug** [comment]
I followed the instructions for the GOG version and put everything where instructed:
![2024-10-16-124423](https://github.com/user-attachments/assets/d1e870a4-4189-43ee-a14b-ebd9d2c930f8)
Is there something I'm missing or did I misinterpret the instructions?

**Comment by PatnosDD** [comment]
Should be good technically.

**Comment by skewbug** [comment]
what possibilities should I look into in order to get this to work? Does this require any plugins I might not have installed?

**Comment by PatnosDD** [comment]
Are you using ftp

**Comment by skewbug** [comment]
I'm using vitashell over usb on a vita 2000. I've repatched and replaced the files several times to make sure it wasn't a file transfer-related issue. I've tried both the steam and gog versions.

**Comment by PatnosDD** [comment]
dm me on discord

@patnosd

**Comment by skewbug** [comment]
it's really not good form to troubleshoot privately...
I suppose I can just comment the solution if we find anything.

**Comment by PatnosDD** [comment]
Well, comments usually take a ton of time, thats why i mostly prefer discord. if game files are correct, it should work perfectly fine. No plugin is known to cause unity based homebrew games to crash, outside trophax which causes them to freeze.

**Comment by skewbug** [comment]
I sent you a friend request on discord, I don't think I can dm you unless we're friends or share a server. Is it possible that something went wrong during the patching process despite it saying that everything went fine? Are there any data files required besides the ones that came from the patch and were installed by the vpk?

**Comment by skewbug** [comment]
Discord does not let me message you because we do not share a server. Is there any other info I can provide you with to better diagnose the error?
