### ISSUE TITLE
Request to add Polish language

### ISSUE THREAD

**Issue by xenobi354** [PatnosDD/Hollow-Knight-PsVita#19]
Hello, would it be possible to add a Polish language? On the internet, on the forum grajpopolsku, there is a Polish version available in the form of two files resources.assets, sharedassets0.assets. I think that if you modify the delta, the Polish version would work

**Comment by PatnosDD** [comment]
Hello. No further updates are planned.

**Comment by Girotin** [comment]
> Hello. No further updates are planned.

Really?? ;-;

I thought you said you wanted to use the experience on the Cuphead port to improve Hollow Knight later 😭

Something happened on the way? New job consuming time, lost interest in the project? Too difficult?

Could you share a quick update? A good amount of people like your work on the Vita friend.
