### ISSUE TITLE
Closed source?

### ISSUE THREAD

**Issue by boozook** [PatnosDD/Hollow-Knight-PsVita#2]
I can't find any source of the port.

**Comment by v-atamanenko** [comment]
@boozook there can't be any source because the game is close-sourced. The port is done via decompiling its Unity project and recompiling it for Vita. And with Unity you only really get a big project file that's not shareable. So it's distributed via a patch you can apply to PC data files

**Comment by boozook** [comment]
Imho, as I'm sure, your personal results of disassembling / decompiling as well as some disasm- and build- scripts can be opened because it's yours. Otherwise this is really closed-source project sadly.

**Comment by v-atamanenko** [comment]
No, pretty sure that unless it's a clean-room reverse engineering, you can't publish any "results" as in code snippets and alike. Per the US law at least, which GitHub honors.

**Comment by boozook** [comment]
As I know (of course I can be wrong) you can because your results is not the same as original source code. Technically it's same as any result of any analyzer or debugger - this is just a thing that produced using "original closed binary".

Anyway you free to share scripts as solution to "make it by myself for myself using my copy of the game". It can't be bad.

**Comment by PatnosDD** [comment]
> I can't find any source of the port.

well I'm pretty sure i never said there was any.

**Comment by cualquiercosa327** [comment]
They can have legal issues if they share the decompilated code as if (it is a Grey area as it is no done clone-room reverse engineering) 
The most viable solution is create a howto file where it is explained what programs (version of them.. are using, being the end user the one who decompilate himself. 

What can be shared is the parts of the code they create to optimize it for making it running on vita as it is code they have build themselves.

**Comment by PatnosDD** [comment]
Well, the tutorial would be 3 books long. Because scripts aren't the only things that were changed.

**Comment by cualquiercosa327** [comment]
Then it had little sense : the howto should be short (1/2 page) ienought to make the user have the same  the decompiled files.  If someone is interested on using the src, he should know how to use it already. 

If no only the diff files (it can be done with the command duff) of the files to see the changes to show the improved things.
