### ISSUE TITLE
C2-12828-1 (FW 3.60 / Enso) 

### ISSUE THREAD

**Issue by l00kanio** [PatnosDD/Hollow-Knight-PsVita#4]
Are there any specific / compatibility requirements? 
I installed port from VitaDB Downloader, then I patched Steam and GOG data files  (yes, I have bought both distributions  :-) ), I got zip file ~406 MB each time, unpacked it, copied it to ux0:app/HKVT12222/ and in both cases game crashes :-( I get C2-12828-1. 

BTW I have common plugins, additionally added mentioned [ThreadOptimizer](https://github.com/GrapheneCt/ThreadOptimizer) but haven't had opportunity to take a snapshot, as the game crashes.

**Comment by l00kanio** [comment]
It was filesystem issue  (do not  recommend neither  FTP files transferring nor copying to sd card on Linux systems) . Sorry for the fuss

**Comment by apes0** [comment]
@l00kanio Hi there, could you elaborate on what went wrong or how you fixed it? I am also encountering this issue on Ubuntu & filezilla (so FTP file transferring). Thanks!

**Comment by l00kanio** [comment]
@apes0  I just did all steps on Windows. Before that, I chkdsk-ed SD which fixed a few errors. After that, it worked. I am not sure if it was Wine's fault (running ApplyPatch) or exfat driver on Linux.

**Comment by apes0** [comment]
@l00kanio Ah ok, thank you!!

**Comment by mav1o1** [comment]
After doing this on windows, I am getting the same error.

**Comment by apes0** [comment]
Hi, i managed to get it working (should work on windows & linux)! I think that the problem is with the file transfer. What i did was to send the whole zip to the vita and then extract it in vitashell. The only issue is that this is very slow.

**Comment by l00kanio** [comment]
Yes, transfer was one of the things I was guessing to be impact factor. Thanks for pointing it so well
