### ISSUE TITLE
MiniVitaTV breaks controls support

### ISSUE THREAD

**Issue by TheUnpunished** [PatnosDD/Hollow-Knight-PsVita#5]
If you have [MiniVitaTV](https://github.com/TheOfficialFloW/MiniVitaTV) installed, controls don't work.

Steps to replicate:
- Go to AutoPlugin 2
- Install MiniVitaTV
- Restart PS Vita
- Launch the game. The controls will not work, no gamepads detected from the Controls section.

What I've tried:
- Uninstalling any input-related plugin, that's not MiniVitaTV
- Trying to use "Vita as virtual DS4" option in ReVita

Additional note:
- I was using the GOG version

**Comment by PatnosDD** [comment]
Hey mate, thanks for reporting the issue. The issues with input are mostly caused by the InControl input manager which is getting removed and replaced with Unity's build in one in the next update.

**Comment by TheUnpunished** [comment]
> replaced with Unity's build in one in the next update.

That's good to hear! If possible, we should raise awareness to some other Vita modders that want to port their Unity games about this particular issue.
