### ISSUE TITLE
Quick Map/Quick Cast not working

### ISSUE THREAD

**Issue by haxxxen** [PatnosDD/Hollow-Knight-PsVita#6]
PSVita Slim
I have tried new 1.09 update, where it says the Quick Accesses are fixed, but it was working fine for me on 1.06 version and now only at Savespot Quick Map is working and I can only Quick Cast, no matter where I touch screen.

**Comment by PatnosDD** [comment]
Did you hold the touchscreen instead of tapping?

**Comment by haxxxen** [comment]
Hi. It makes no difference of holding or just tapping the screen, and it only works on left side of screen and only quick cast. On a savespot however, the quick map works. This was not the case for me with the 1.06 version, the first I have tried. There, both were working fine, but some cutscenes were skipped. Have to check with 1.09 version.
