### ISSUE TITLE
save compatibility

### ISSUE THREAD

**Issue by gwlegion** [PatnosDD/Hollow-Knight-PsVita#7]
hi  ... not really an issue, but are savegames compatibles between windows steam version and this port ?

**Comment by PatnosDD** [comment]
Hello, yes.

**Comment by gwlegion** [comment]
ty for the answer ... but how ? 
were are the save on the vita ?

**Comment by PatnosDD** [comment]
Its in ux0:/data directly

**Comment by gwlegion** [comment]
ty, it works ... i'm very happy to have this great game on this great handheld ... very good works
